// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// OpenpitrixModifyAttributeRequest openpitrix modify attribute request
// swagger:model openpitrixModifyAttributeRequest
type OpenpitrixModifyAttributeRequest struct {

	// attribute id
	AttributeID string `json:"attribute_id,omitempty"`

	// attribute name id
	AttributeNameID string `json:"attribute_name_id,omitempty"`

	// attribute unit id
	AttributeUnitID string `json:"attribute_unit_id,omitempty"`

	// value
	Value string `json:"value,omitempty"`
}

// Validate validates this openpitrix modify attribute request
func (m *OpenpitrixModifyAttributeRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *OpenpitrixModifyAttributeRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OpenpitrixModifyAttributeRequest) UnmarshalBinary(b []byte) error {
	var res OpenpitrixModifyAttributeRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
