// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// OpenpitrixModifyPriceRequest openpitrix modify price request
// swagger:model openpitrixModifyPriceRequest
type OpenpitrixModifyPriceRequest struct {

	// attribute id
	AttributeID string `json:"attribute_id,omitempty"`

	// end time
	EndTime strfmt.DateTime `json:"end_time,omitempty"`

	// price id
	PriceID string `json:"price_id,omitempty"`

	// sku id
	SkuID string `json:"sku_id,omitempty"`

	// start time
	StartTime strfmt.DateTime `json:"start_time,omitempty"`

	// status
	Status string `json:"status,omitempty"`
}

// Validate validates this openpitrix modify price request
func (m *OpenpitrixModifyPriceRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *OpenpitrixModifyPriceRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OpenpitrixModifyPriceRequest) UnmarshalBinary(b []byte) error {
	var res OpenpitrixModifyPriceRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
