// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// OpenpitrixDescribeCombinationSkusResponse openpitrix describe combination skus response
// swagger:model openpitrixDescribeCombinationSkusResponse
type OpenpitrixDescribeCombinationSkusResponse struct {

	// combination sku set
	CombinationSkuSet OpenpitrixDescribeCombinationSkusResponseCombinationSkuSet `json:"combination_sku_set"`

	// total count
	TotalCount int64 `json:"total_count,omitempty"`
}

// Validate validates this openpitrix describe combination skus response
func (m *OpenpitrixDescribeCombinationSkusResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *OpenpitrixDescribeCombinationSkusResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OpenpitrixDescribeCombinationSkusResponse) UnmarshalBinary(b []byte) error {
	var res OpenpitrixDescribeCombinationSkusResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
