// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// OpenpitrixCommonMeteringsResponse openpitrix common meterings response
// swagger:model openpitrixCommonMeteringsResponse
type OpenpitrixCommonMeteringsResponse struct {

	// resource ids
	ResourceIds []string `json:"resource_ids"`
}

// Validate validates this openpitrix common meterings response
func (m *OpenpitrixCommonMeteringsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateResourceIds(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OpenpitrixCommonMeteringsResponse) validateResourceIds(formats strfmt.Registry) error {

	if swag.IsZero(m.ResourceIds) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *OpenpitrixCommonMeteringsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OpenpitrixCommonMeteringsResponse) UnmarshalBinary(b []byte) error {
	var res OpenpitrixCommonMeteringsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
