// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// OpenpitrixDeleteSpusRequest openpitrix delete spus request
// swagger:model openpitrixDeleteSpusRequest
type OpenpitrixDeleteSpusRequest struct {

	// spu ids
	SpuIds []string `json:"spu_ids"`
}

// Validate validates this openpitrix delete spus request
func (m *OpenpitrixDeleteSpusRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSpuIds(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OpenpitrixDeleteSpusRequest) validateSpuIds(formats strfmt.Registry) error {

	if swag.IsZero(m.SpuIds) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *OpenpitrixDeleteSpusRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OpenpitrixDeleteSpusRequest) UnmarshalBinary(b []byte) error {
	var res OpenpitrixDeleteSpusRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
