// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// OpenpitrixDeleteProbationsRequest openpitrix delete probations request
// swagger:model openpitrixDeleteProbationsRequest
type OpenpitrixDeleteProbationsRequest struct {

	// probation ids
	ProbationIds []string `json:"probation_ids"`
}

// Validate validates this openpitrix delete probations request
func (m *OpenpitrixDeleteProbationsRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateProbationIds(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OpenpitrixDeleteProbationsRequest) validateProbationIds(formats strfmt.Registry) error {

	if swag.IsZero(m.ProbationIds) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *OpenpitrixDeleteProbationsRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OpenpitrixDeleteProbationsRequest) UnmarshalBinary(b []byte) error {
	var res OpenpitrixDeleteProbationsRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
