// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// OpenpitrixDeletePricesResponse openpitrix delete prices response
// swagger:model openpitrixDeletePricesResponse
type OpenpitrixDeletePricesResponse struct {

	// price ids
	PriceIds []string `json:"price_ids"`
}

// Validate validates this openpitrix delete prices response
func (m *OpenpitrixDeletePricesResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePriceIds(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OpenpitrixDeletePricesResponse) validatePriceIds(formats strfmt.Registry) error {

	if swag.IsZero(m.PriceIds) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *OpenpitrixDeletePricesResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OpenpitrixDeletePricesResponse) UnmarshalBinary(b []byte) error {
	var res OpenpitrixDeletePricesResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
