// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// OpenpitrixDeleteCouponReceivedsRequest openpitrix delete coupon receiveds request
// swagger:model openpitrixDeleteCouponReceivedsRequest
type OpenpitrixDeleteCouponReceivedsRequest struct {

	// coupon received ids
	CouponReceivedIds []string `json:"coupon_received_ids"`
}

// Validate validates this openpitrix delete coupon receiveds request
func (m *OpenpitrixDeleteCouponReceivedsRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCouponReceivedIds(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OpenpitrixDeleteCouponReceivedsRequest) validateCouponReceivedIds(formats strfmt.Registry) error {

	if swag.IsZero(m.CouponReceivedIds) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *OpenpitrixDeleteCouponReceivedsRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OpenpitrixDeleteCouponReceivedsRequest) UnmarshalBinary(b []byte) error {
	var res OpenpitrixDeleteCouponReceivedsRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
