// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// OpenpitrixModifySpuRequest openpitrix modify spu request
// swagger:model openpitrixModifySpuRequest
type OpenpitrixModifySpuRequest struct {

	// product id
	ProductID string `json:"product_id,omitempty"`

	// spu id
	SpuID string `json:"spu_id,omitempty"`
}

// Validate validates this openpitrix modify spu request
func (m *OpenpitrixModifySpuRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *OpenpitrixModifySpuRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OpenpitrixModifySpuRequest) UnmarshalBinary(b []byte) error {
	var res OpenpitrixModifySpuRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
