// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// OpenpitrixModifySkuResponse openpitrix modify sku response
// swagger:model openpitrixModifySkuResponse
type OpenpitrixModifySkuResponse struct {

	// sku id
	SkuID string `json:"sku_id,omitempty"`
}

// Validate validates this openpitrix modify sku response
func (m *OpenpitrixModifySkuResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *OpenpitrixModifySkuResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OpenpitrixModifySkuResponse) UnmarshalBinary(b []byte) error {
	var res OpenpitrixModifySkuResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
