// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// OpenpitrixModifyCombinationSkuRequest openpitrix modify combination sku request
// swagger:model openpitrixModifyCombinationSkuRequest
type OpenpitrixModifyCombinationSkuRequest struct {

	// combination id
	CombinationID string `json:"combination_id,omitempty"`

	// combination sku id
	CombinationSkuID string `json:"combination_sku_id,omitempty"`

	// sku id
	SkuID string `json:"sku_id,omitempty"`
}

// Validate validates this openpitrix modify combination sku request
func (m *OpenpitrixModifyCombinationSkuRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *OpenpitrixModifyCombinationSkuRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OpenpitrixModifyCombinationSkuRequest) UnmarshalBinary(b []byte) error {
	var res OpenpitrixModifyCombinationSkuRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
