// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// OpenpitrixModifyDiscountRequest openpitrix modify discount request
// swagger:model openpitrixModifyDiscountRequest
type OpenpitrixModifyDiscountRequest struct {

	// description
	Description string `json:"description,omitempty"`

	// discount id
	DiscountID string `json:"discount_id,omitempty"`

	// discount percent
	DiscountPercent float64 `json:"discount_percent,omitempty"`

	// discount value
	DiscountValue float64 `json:"discount_value,omitempty"`

	// end time
	EndTime strfmt.DateTime `json:"end_time,omitempty"`

	// limit ids
	LimitIds []string `json:"limit_ids"`

	// name
	Name string `json:"name,omitempty"`

	// start time
	StartTime strfmt.DateTime `json:"start_time,omitempty"`
}

// Validate validates this openpitrix modify discount request
func (m *OpenpitrixModifyDiscountRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLimitIds(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OpenpitrixModifyDiscountRequest) validateLimitIds(formats strfmt.Registry) error {

	if swag.IsZero(m.LimitIds) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *OpenpitrixModifyDiscountRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OpenpitrixModifyDiscountRequest) UnmarshalBinary(b []byte) error {
	var res OpenpitrixModifyDiscountRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
