// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// OpenpitrixCreateCouponRequest openpitrix create coupon request
// swagger:model openpitrixCreateCouponRequest
type OpenpitrixCreateCouponRequest struct {

	// balance
	Balance float64 `json:"balance,omitempty"`

	// count
	Count int64 `json:"count,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// end time
	EndTime strfmt.DateTime `json:"end_time,omitempty"`

	// limit ids
	LimitIds []string `json:"limit_ids"`

	// limit num per
	LimitNumPer int64 `json:"limit_num_per,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// start time
	StartTime strfmt.DateTime `json:"start_time,omitempty"`
}

// Validate validates this openpitrix create coupon request
func (m *OpenpitrixCreateCouponRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLimitIds(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OpenpitrixCreateCouponRequest) validateLimitIds(formats strfmt.Registry) error {

	if swag.IsZero(m.LimitIds) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *OpenpitrixCreateCouponRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OpenpitrixCreateCouponRequest) UnmarshalBinary(b []byte) error {
	var res OpenpitrixCreateCouponRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
