// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// OpenpitrixModifyAttributeUnitRequest openpitrix modify attribute unit request
// swagger:model openpitrixModifyAttributeUnitRequest
type OpenpitrixModifyAttributeUnitRequest struct {

	// attribute unit id
	AttributeUnitID string `json:"attribute_unit_id,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this openpitrix modify attribute unit request
func (m *OpenpitrixModifyAttributeUnitRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *OpenpitrixModifyAttributeUnitRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OpenpitrixModifyAttributeUnitRequest) UnmarshalBinary(b []byte) error {
	var res OpenpitrixModifyAttributeUnitRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
