// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// OpenpitrixDescribeWithdrawsResponse openpitrix describe withdraws response
// swagger:model openpitrixDescribeWithdrawsResponse
type OpenpitrixDescribeWithdrawsResponse struct {

	// total count
	TotalCount int64 `json:"total_count,omitempty"`

	// withdraw set
	WithdrawSet OpenpitrixDescribeWithdrawsResponseWithdrawSet `json:"withdraw_set"`
}

// Validate validates this openpitrix describe withdraws response
func (m *OpenpitrixDescribeWithdrawsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *OpenpitrixDescribeWithdrawsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OpenpitrixDescribeWithdrawsResponse) UnmarshalBinary(b []byte) error {
	var res OpenpitrixDescribeWithdrawsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
