// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// OpenpitrixIncome openpitrix income
// swagger:model openpitrixIncome
type OpenpitrixIncome struct {

	// balance
	Balance float64 `json:"balance,omitempty"`

	// contract id
	ContractID string `json:"contract_id,omitempty"`

	// create time
	CreateTime strfmt.DateTime `json:"create_time,omitempty"`

	// currency
	Currency string `json:"currency,omitempty"`

	// income id
	IncomeID string `json:"income_id,omitempty"`

	// owner id
	OwnerID string `json:"owner_id,omitempty"`
}

// Validate validates this openpitrix income
func (m *OpenpitrixIncome) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *OpenpitrixIncome) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OpenpitrixIncome) UnmarshalBinary(b []byte) error {
	var res OpenpitrixIncome
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
