// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// OpenpitrixModifyCombinationPriceRequest openpitrix modify combination price request
// swagger:model openpitrixModifyCombinationPriceRequest
type OpenpitrixModifyCombinationPriceRequest struct {

	// attribute id
	AttributeID string `json:"attribute_id,omitempty"`

	// combination price id
	CombinationPriceID string `json:"combination_price_id,omitempty"`

	// combination sku id
	CombinationSkuID string `json:"combination_sku_id,omitempty"`

	// currency
	Currency OpenpitrixCurrency `json:"currency,omitempty"`

	// prices
	Prices map[string]float64 `json:"prices,omitempty"`
}

// Validate validates this openpitrix modify combination price request
func (m *OpenpitrixModifyCombinationPriceRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCurrency(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OpenpitrixModifyCombinationPriceRequest) validateCurrency(formats strfmt.Registry) error {

	if swag.IsZero(m.Currency) { // not required
		return nil
	}

	if err := m.Currency.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("currency")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *OpenpitrixModifyCombinationPriceRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OpenpitrixModifyCombinationPriceRequest) UnmarshalBinary(b []byte) error {
	var res OpenpitrixModifyCombinationPriceRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
