// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// OpenpitrixDeleteSkusResponse openpitrix delete skus response
// swagger:model openpitrixDeleteSkusResponse
type OpenpitrixDeleteSkusResponse struct {

	// sku ids
	SkuIds []string `json:"sku_ids"`
}

// Validate validates this openpitrix delete skus response
func (m *OpenpitrixDeleteSkusResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSkuIds(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OpenpitrixDeleteSkusResponse) validateSkuIds(formats strfmt.Registry) error {

	if swag.IsZero(m.SkuIds) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *OpenpitrixDeleteSkusResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OpenpitrixDeleteSkusResponse) UnmarshalBinary(b []byte) error {
	var res OpenpitrixDeleteSkusResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
