// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// OpenpitrixDeleteCombinationsResponse openpitrix delete combinations response
// swagger:model openpitrixDeleteCombinationsResponse
type OpenpitrixDeleteCombinationsResponse struct {

	// combination ids
	CombinationIds []string `json:"combination_ids"`
}

// Validate validates this openpitrix delete combinations response
func (m *OpenpitrixDeleteCombinationsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCombinationIds(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OpenpitrixDeleteCombinationsResponse) validateCombinationIds(formats strfmt.Registry) error {

	if swag.IsZero(m.CombinationIds) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *OpenpitrixDeleteCombinationsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OpenpitrixDeleteCombinationsResponse) UnmarshalBinary(b []byte) error {
	var res OpenpitrixDeleteCombinationsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
