// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// OpenpitrixCreateCombinationRequest openpitrix create combination request
// swagger:model openpitrixCreateCombinationRequest
type OpenpitrixCreateCombinationRequest struct {

	// description
	Description string `json:"description,omitempty"`

	// end time
	EndTime strfmt.DateTime `json:"end_time,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// start time
	StartTime strfmt.DateTime `json:"start_time,omitempty"`
}

// Validate validates this openpitrix create combination request
func (m *OpenpitrixCreateCombinationRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *OpenpitrixCreateCombinationRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OpenpitrixCreateCombinationRequest) UnmarshalBinary(b []byte) error {
	var res OpenpitrixCreateCombinationRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
