// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// UpdateMeteringValueUpdateValueTypes update metering value update value types
// swagger:model UpdateMeteringValueUpdateValueTypes
type UpdateMeteringValueUpdateValueTypes string

const (
	// UpdateMeteringValueUpdateValueTypesINCREMENTAL captures enum value "INCREMENTAL"
	UpdateMeteringValueUpdateValueTypesINCREMENTAL UpdateMeteringValueUpdateValueTypes = "INCREMENTAL"
	// UpdateMeteringValueUpdateValueTypesREPLACE captures enum value "REPLACE"
	UpdateMeteringValueUpdateValueTypesREPLACE UpdateMeteringValueUpdateValueTypes = "REPLACE"
)

// for schema
var updateMeteringValueUpdateValueTypesEnum []interface{}

func init() {
	var res []UpdateMeteringValueUpdateValueTypes
	if err := json.Unmarshal([]byte(`["INCREMENTAL","REPLACE"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		updateMeteringValueUpdateValueTypesEnum = append(updateMeteringValueUpdateValueTypesEnum, v)
	}
}

func (m UpdateMeteringValueUpdateValueTypes) validateUpdateMeteringValueUpdateValueTypesEnum(path, location string, value UpdateMeteringValueUpdateValueTypes) error {
	if err := validate.Enum(path, location, value, updateMeteringValueUpdateValueTypesEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this update metering value update value types
func (m UpdateMeteringValueUpdateValueTypes) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateUpdateMeteringValueUpdateValueTypesEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
