// Code generated by go-swagger; DO NOT EDIT.

package promotion_sku_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"openpitrix.io/openpitrix/test/models"
)

// NewCreateCombinationSkuParams creates a new CreateCombinationSkuParams object
// with the default values initialized.
func NewCreateCombinationSkuParams() *CreateCombinationSkuParams {
	var ()
	return &CreateCombinationSkuParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateCombinationSkuParamsWithTimeout creates a new CreateCombinationSkuParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateCombinationSkuParamsWithTimeout(timeout time.Duration) *CreateCombinationSkuParams {
	var ()
	return &CreateCombinationSkuParams{

		timeout: timeout,
	}
}

// NewCreateCombinationSkuParamsWithContext creates a new CreateCombinationSkuParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateCombinationSkuParamsWithContext(ctx context.Context) *CreateCombinationSkuParams {
	var ()
	return &CreateCombinationSkuParams{

		Context: ctx,
	}
}

// NewCreateCombinationSkuParamsWithHTTPClient creates a new CreateCombinationSkuParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateCombinationSkuParamsWithHTTPClient(client *http.Client) *CreateCombinationSkuParams {
	var ()
	return &CreateCombinationSkuParams{
		HTTPClient: client,
	}
}

/*CreateCombinationSkuParams contains all the parameters to send to the API endpoint
for the create combination sku operation typically these are written to a http.Request
*/
type CreateCombinationSkuParams struct {

	/*Body*/
	Body *models.OpenpitrixCreateCombinationSkuRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create combination sku params
func (o *CreateCombinationSkuParams) WithTimeout(timeout time.Duration) *CreateCombinationSkuParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create combination sku params
func (o *CreateCombinationSkuParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create combination sku params
func (o *CreateCombinationSkuParams) WithContext(ctx context.Context) *CreateCombinationSkuParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create combination sku params
func (o *CreateCombinationSkuParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create combination sku params
func (o *CreateCombinationSkuParams) WithHTTPClient(client *http.Client) *CreateCombinationSkuParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create combination sku params
func (o *CreateCombinationSkuParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create combination sku params
func (o *CreateCombinationSkuParams) WithBody(body *models.OpenpitrixCreateCombinationSkuRequest) *CreateCombinationSkuParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create combination sku params
func (o *CreateCombinationSkuParams) SetBody(body *models.OpenpitrixCreateCombinationSkuRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateCombinationSkuParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
