// Code generated by go-swagger; DO NOT EDIT.

package promotion_sku_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"openpitrix.io/openpitrix/test/models"
)

// NewCreateCombinationParams creates a new CreateCombinationParams object
// with the default values initialized.
func NewCreateCombinationParams() *CreateCombinationParams {
	var ()
	return &CreateCombinationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateCombinationParamsWithTimeout creates a new CreateCombinationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateCombinationParamsWithTimeout(timeout time.Duration) *CreateCombinationParams {
	var ()
	return &CreateCombinationParams{

		timeout: timeout,
	}
}

// NewCreateCombinationParamsWithContext creates a new CreateCombinationParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateCombinationParamsWithContext(ctx context.Context) *CreateCombinationParams {
	var ()
	return &CreateCombinationParams{

		Context: ctx,
	}
}

// NewCreateCombinationParamsWithHTTPClient creates a new CreateCombinationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateCombinationParamsWithHTTPClient(client *http.Client) *CreateCombinationParams {
	var ()
	return &CreateCombinationParams{
		HTTPClient: client,
	}
}

/*CreateCombinationParams contains all the parameters to send to the API endpoint
for the create combination operation typically these are written to a http.Request
*/
type CreateCombinationParams struct {

	/*Body*/
	Body *models.OpenpitrixCreateCombinationRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create combination params
func (o *CreateCombinationParams) WithTimeout(timeout time.Duration) *CreateCombinationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create combination params
func (o *CreateCombinationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create combination params
func (o *CreateCombinationParams) WithContext(ctx context.Context) *CreateCombinationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create combination params
func (o *CreateCombinationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create combination params
func (o *CreateCombinationParams) WithHTTPClient(client *http.Client) *CreateCombinationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create combination params
func (o *CreateCombinationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create combination params
func (o *CreateCombinationParams) WithBody(body *models.OpenpitrixCreateCombinationRequest) *CreateCombinationParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create combination params
func (o *CreateCombinationParams) SetBody(body *models.OpenpitrixCreateCombinationRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateCombinationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
