// Code generated by go-swagger; DO NOT EDIT.

package promotion_sku_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"openpitrix.io/openpitrix/test/models"
)

// DeleteCombinationSkusReader is a Reader for the DeleteCombinationSkus structure.
type DeleteCombinationSkusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteCombinationSkusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteCombinationSkusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteCombinationSkusOK creates a DeleteCombinationSkusOK with default headers values
func NewDeleteCombinationSkusOK() *DeleteCombinationSkusOK {
	return &DeleteCombinationSkusOK{}
}

/*DeleteCombinationSkusOK handles this case with default header values.

A successful response.
*/
type DeleteCombinationSkusOK struct {
	Payload *models.OpenpitrixDeleteCombinationSkusResponse
}

func (o *DeleteCombinationSkusOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/metering/combination/skus][%d] deleteCombinationSkusOK  %+v", 200, o.Payload)
}

func (o *DeleteCombinationSkusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OpenpitrixDeleteCombinationSkusResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
