// Code generated by go-swagger; DO NOT EDIT.

package promotion_sku_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"openpitrix.io/openpitrix/test/models"
)

// DescribeCombinationSkusReader is a Reader for the DescribeCombinationSkus structure.
type DescribeCombinationSkusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DescribeCombinationSkusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDescribeCombinationSkusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDescribeCombinationSkusOK creates a DescribeCombinationSkusOK with default headers values
func NewDescribeCombinationSkusOK() *DescribeCombinationSkusOK {
	return &DescribeCombinationSkusOK{}
}

/*DescribeCombinationSkusOK handles this case with default header values.

A successful response.
*/
type DescribeCombinationSkusOK struct {
	Payload *models.OpenpitrixDescribeCombinationSkusResponse
}

func (o *DescribeCombinationSkusOK) Error() string {
	return fmt.Sprintf("[GET /v1/metering/combination/skus][%d] describeCombinationSkusOK  %+v", 200, o.Payload)
}

func (o *DescribeCombinationSkusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OpenpitrixDescribeCombinationSkusResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
