// Code generated by go-swagger; DO NOT EDIT.

package promotion_sku_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"openpitrix.io/openpitrix/test/models"
)

// ModifyCombinationReader is a Reader for the ModifyCombination structure.
type ModifyCombinationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ModifyCombinationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewModifyCombinationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewModifyCombinationOK creates a ModifyCombinationOK with default headers values
func NewModifyCombinationOK() *ModifyCombinationOK {
	return &ModifyCombinationOK{}
}

/*ModifyCombinationOK handles this case with default header values.

A successful response.
*/
type ModifyCombinationOK struct {
	Payload *models.OpenpitrixModifyCombinationResponse
}

func (o *ModifyCombinationOK) Error() string {
	return fmt.Sprintf("[PUT /v1/metering/combination][%d] modifyCombinationOK  %+v", 200, o.Payload)
}

func (o *ModifyCombinationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OpenpitrixModifyCombinationResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
