// Code generated by go-swagger; DO NOT EDIT.

package metering_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"openpitrix.io/openpitrix/test/models"
)

// NewStartMeteringsParams creates a new StartMeteringsParams object
// with the default values initialized.
func NewStartMeteringsParams() *StartMeteringsParams {
	var ()
	return &StartMeteringsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewStartMeteringsParamsWithTimeout creates a new StartMeteringsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewStartMeteringsParamsWithTimeout(timeout time.Duration) *StartMeteringsParams {
	var ()
	return &StartMeteringsParams{

		timeout: timeout,
	}
}

// NewStartMeteringsParamsWithContext creates a new StartMeteringsParams object
// with the default values initialized, and the ability to set a context for a request
func NewStartMeteringsParamsWithContext(ctx context.Context) *StartMeteringsParams {
	var ()
	return &StartMeteringsParams{

		Context: ctx,
	}
}

// NewStartMeteringsParamsWithHTTPClient creates a new StartMeteringsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewStartMeteringsParamsWithHTTPClient(client *http.Client) *StartMeteringsParams {
	var ()
	return &StartMeteringsParams{
		HTTPClient: client,
	}
}

/*StartMeteringsParams contains all the parameters to send to the API endpoint
for the start meterings operation typically these are written to a http.Request
*/
type StartMeteringsParams struct {

	/*Body*/
	Body *models.OpenpitrixStartMeteringsRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the start meterings params
func (o *StartMeteringsParams) WithTimeout(timeout time.Duration) *StartMeteringsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the start meterings params
func (o *StartMeteringsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the start meterings params
func (o *StartMeteringsParams) WithContext(ctx context.Context) *StartMeteringsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the start meterings params
func (o *StartMeteringsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the start meterings params
func (o *StartMeteringsParams) WithHTTPClient(client *http.Client) *StartMeteringsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the start meterings params
func (o *StartMeteringsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the start meterings params
func (o *StartMeteringsParams) WithBody(body *models.OpenpitrixStartMeteringsRequest) *StartMeteringsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the start meterings params
func (o *StartMeteringsParams) SetBody(body *models.OpenpitrixStartMeteringsRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *StartMeteringsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
