// Code generated by go-swagger; DO NOT EDIT.

package metering_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"openpitrix.io/openpitrix/test/models"
)

// TerminateMeteringsReader is a Reader for the TerminateMeterings structure.
type TerminateMeteringsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TerminateMeteringsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewTerminateMeteringsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewTerminateMeteringsOK creates a TerminateMeteringsOK with default headers values
func NewTerminateMeteringsOK() *TerminateMeteringsOK {
	return &TerminateMeteringsOK{}
}

/*TerminateMeteringsOK handles this case with default header values.

A successful response.
*/
type TerminateMeteringsOK struct {
	Payload *models.OpenpitrixCommonMeteringsResponse
}

func (o *TerminateMeteringsOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/metering][%d] terminateMeteringsOK  %+v", 200, o.Payload)
}

func (o *TerminateMeteringsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OpenpitrixCommonMeteringsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
