// Code generated by go-swagger; DO NOT EDIT.

package metering_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"openpitrix.io/openpitrix/test/models"
)

// NewTerminateMeteringsParams creates a new TerminateMeteringsParams object
// with the default values initialized.
func NewTerminateMeteringsParams() *TerminateMeteringsParams {
	var ()
	return &TerminateMeteringsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewTerminateMeteringsParamsWithTimeout creates a new TerminateMeteringsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewTerminateMeteringsParamsWithTimeout(timeout time.Duration) *TerminateMeteringsParams {
	var ()
	return &TerminateMeteringsParams{

		timeout: timeout,
	}
}

// NewTerminateMeteringsParamsWithContext creates a new TerminateMeteringsParams object
// with the default values initialized, and the ability to set a context for a request
func NewTerminateMeteringsParamsWithContext(ctx context.Context) *TerminateMeteringsParams {
	var ()
	return &TerminateMeteringsParams{

		Context: ctx,
	}
}

// NewTerminateMeteringsParamsWithHTTPClient creates a new TerminateMeteringsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewTerminateMeteringsParamsWithHTTPClient(client *http.Client) *TerminateMeteringsParams {
	var ()
	return &TerminateMeteringsParams{
		HTTPClient: client,
	}
}

/*TerminateMeteringsParams contains all the parameters to send to the API endpoint
for the terminate meterings operation typically these are written to a http.Request
*/
type TerminateMeteringsParams struct {

	/*Body*/
	Body *models.OpenpitrixTerminateMeteringsRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the terminate meterings params
func (o *TerminateMeteringsParams) WithTimeout(timeout time.Duration) *TerminateMeteringsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the terminate meterings params
func (o *TerminateMeteringsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the terminate meterings params
func (o *TerminateMeteringsParams) WithContext(ctx context.Context) *TerminateMeteringsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the terminate meterings params
func (o *TerminateMeteringsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the terminate meterings params
func (o *TerminateMeteringsParams) WithHTTPClient(client *http.Client) *TerminateMeteringsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the terminate meterings params
func (o *TerminateMeteringsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the terminate meterings params
func (o *TerminateMeteringsParams) WithBody(body *models.OpenpitrixTerminateMeteringsRequest) *TerminateMeteringsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the terminate meterings params
func (o *TerminateMeteringsParams) SetBody(body *models.OpenpitrixTerminateMeteringsRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *TerminateMeteringsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
