// Code generated by go-swagger; DO NOT EDIT.

package sku_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"openpitrix.io/openpitrix/test/models"
)

// CreateAttributeReader is a Reader for the CreateAttribute structure.
type CreateAttributeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateAttributeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCreateAttributeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateAttributeOK creates a CreateAttributeOK with default headers values
func NewCreateAttributeOK() *CreateAttributeOK {
	return &CreateAttributeOK{}
}

/*CreateAttributeOK handles this case with default header values.

A successful response.
*/
type CreateAttributeOK struct {
	Payload *models.OpenpitrixCreateAttributeResponse
}

func (o *CreateAttributeOK) Error() string {
	return fmt.Sprintf("[POST /v1/metering/attribute][%d] createAttributeOK  %+v", 200, o.Payload)
}

func (o *CreateAttributeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OpenpitrixCreateAttributeResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
