// Code generated by go-swagger; DO NOT EDIT.

package sku_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"openpitrix.io/openpitrix/test/models"
)

// NewCreateSkuParams creates a new CreateSkuParams object
// with the default values initialized.
func NewCreateSkuParams() *CreateSkuParams {
	var ()
	return &CreateSkuParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateSkuParamsWithTimeout creates a new CreateSkuParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateSkuParamsWithTimeout(timeout time.Duration) *CreateSkuParams {
	var ()
	return &CreateSkuParams{

		timeout: timeout,
	}
}

// NewCreateSkuParamsWithContext creates a new CreateSkuParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateSkuParamsWithContext(ctx context.Context) *CreateSkuParams {
	var ()
	return &CreateSkuParams{

		Context: ctx,
	}
}

// NewCreateSkuParamsWithHTTPClient creates a new CreateSkuParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateSkuParamsWithHTTPClient(client *http.Client) *CreateSkuParams {
	var ()
	return &CreateSkuParams{
		HTTPClient: client,
	}
}

/*CreateSkuParams contains all the parameters to send to the API endpoint
for the create sku operation typically these are written to a http.Request
*/
type CreateSkuParams struct {

	/*Body*/
	Body *models.OpenpitrixCreateSkuRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create sku params
func (o *CreateSkuParams) WithTimeout(timeout time.Duration) *CreateSkuParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create sku params
func (o *CreateSkuParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create sku params
func (o *CreateSkuParams) WithContext(ctx context.Context) *CreateSkuParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create sku params
func (o *CreateSkuParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create sku params
func (o *CreateSkuParams) WithHTTPClient(client *http.Client) *CreateSkuParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create sku params
func (o *CreateSkuParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create sku params
func (o *CreateSkuParams) WithBody(body *models.OpenpitrixCreateSkuRequest) *CreateSkuParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create sku params
func (o *CreateSkuParams) SetBody(body *models.OpenpitrixCreateSkuRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateSkuParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
