// Code generated by go-swagger; DO NOT EDIT.

package sku_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"openpitrix.io/openpitrix/test/models"
)

// NewCreateAttributeUnitParams creates a new CreateAttributeUnitParams object
// with the default values initialized.
func NewCreateAttributeUnitParams() *CreateAttributeUnitParams {
	var ()
	return &CreateAttributeUnitParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateAttributeUnitParamsWithTimeout creates a new CreateAttributeUnitParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateAttributeUnitParamsWithTimeout(timeout time.Duration) *CreateAttributeUnitParams {
	var ()
	return &CreateAttributeUnitParams{

		timeout: timeout,
	}
}

// NewCreateAttributeUnitParamsWithContext creates a new CreateAttributeUnitParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateAttributeUnitParamsWithContext(ctx context.Context) *CreateAttributeUnitParams {
	var ()
	return &CreateAttributeUnitParams{

		Context: ctx,
	}
}

// NewCreateAttributeUnitParamsWithHTTPClient creates a new CreateAttributeUnitParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateAttributeUnitParamsWithHTTPClient(client *http.Client) *CreateAttributeUnitParams {
	var ()
	return &CreateAttributeUnitParams{
		HTTPClient: client,
	}
}

/*CreateAttributeUnitParams contains all the parameters to send to the API endpoint
for the create attribute unit operation typically these are written to a http.Request
*/
type CreateAttributeUnitParams struct {

	/*Body*/
	Body *models.OpenpitrixCreateAttributeUnitRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create attribute unit params
func (o *CreateAttributeUnitParams) WithTimeout(timeout time.Duration) *CreateAttributeUnitParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create attribute unit params
func (o *CreateAttributeUnitParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create attribute unit params
func (o *CreateAttributeUnitParams) WithContext(ctx context.Context) *CreateAttributeUnitParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create attribute unit params
func (o *CreateAttributeUnitParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create attribute unit params
func (o *CreateAttributeUnitParams) WithHTTPClient(client *http.Client) *CreateAttributeUnitParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create attribute unit params
func (o *CreateAttributeUnitParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create attribute unit params
func (o *CreateAttributeUnitParams) WithBody(body *models.OpenpitrixCreateAttributeUnitRequest) *CreateAttributeUnitParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create attribute unit params
func (o *CreateAttributeUnitParams) SetBody(body *models.OpenpitrixCreateAttributeUnitRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateAttributeUnitParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
