// Code generated by go-swagger; DO NOT EDIT.

package sku_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"openpitrix.io/openpitrix/test/models"
)

// CreateSpuReader is a Reader for the CreateSpu structure.
type CreateSpuReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateSpuReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCreateSpuOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateSpuOK creates a CreateSpuOK with default headers values
func NewCreateSpuOK() *CreateSpuOK {
	return &CreateSpuOK{}
}

/*CreateSpuOK handles this case with default header values.

A successful response.
*/
type CreateSpuOK struct {
	Payload *models.OpenpitrixCreateSpuResponse
}

func (o *CreateSpuOK) Error() string {
	return fmt.Sprintf("[POST /v1/metering/spu][%d] createSpuOK  %+v", 200, o.Payload)
}

func (o *CreateSpuOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OpenpitrixCreateSpuResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
