// Code generated by go-swagger; DO NOT EDIT.

package sku_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"openpitrix.io/openpitrix/test/models"
)

// CreateSkuReader is a Reader for the CreateSku structure.
type CreateSkuReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateSkuReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCreateSkuOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateSkuOK creates a CreateSkuOK with default headers values
func NewCreateSkuOK() *CreateSkuOK {
	return &CreateSkuOK{}
}

/*CreateSkuOK handles this case with default header values.

A successful response.
*/
type CreateSkuOK struct {
	Payload *models.OpenpitrixCreateSkuResponse
}

func (o *CreateSkuOK) Error() string {
	return fmt.Sprintf("[POST /v1/metering/sku][%d] createSkuOK  %+v", 200, o.Payload)
}

func (o *CreateSkuOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OpenpitrixCreateSkuResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
