// Code generated by go-swagger; DO NOT EDIT.

package sku_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"openpitrix.io/openpitrix/test/models"
)

// CreateAttributeUnitReader is a Reader for the CreateAttributeUnit structure.
type CreateAttributeUnitReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateAttributeUnitReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCreateAttributeUnitOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateAttributeUnitOK creates a CreateAttributeUnitOK with default headers values
func NewCreateAttributeUnitOK() *CreateAttributeUnitOK {
	return &CreateAttributeUnitOK{}
}

/*CreateAttributeUnitOK handles this case with default header values.

A successful response.
*/
type CreateAttributeUnitOK struct {
	Payload *models.OpenpitrixCreateAttributeUnitResponse
}

func (o *CreateAttributeUnitOK) Error() string {
	return fmt.Sprintf("[POST /v1/metering/attribute/unit][%d] createAttributeUnitOK  %+v", 200, o.Payload)
}

func (o *CreateAttributeUnitOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OpenpitrixCreateAttributeUnitResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
