// Code generated by go-swagger; DO NOT EDIT.

package sku_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"openpitrix.io/openpitrix/test/models"
)

// CreateAttributeNameReader is a Reader for the CreateAttributeName structure.
type CreateAttributeNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateAttributeNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCreateAttributeNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateAttributeNameOK creates a CreateAttributeNameOK with default headers values
func NewCreateAttributeNameOK() *CreateAttributeNameOK {
	return &CreateAttributeNameOK{}
}

/*CreateAttributeNameOK handles this case with default header values.

A successful response.
*/
type CreateAttributeNameOK struct {
	Payload *models.OpenpitrixCreateAttributeNameResponse
}

func (o *CreateAttributeNameOK) Error() string {
	return fmt.Sprintf("[POST /v1/metering/attribute/name][%d] createAttributeNameOK  %+v", 200, o.Payload)
}

func (o *CreateAttributeNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OpenpitrixCreateAttributeNameResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
