// Code generated by go-swagger; DO NOT EDIT.

package sku_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"openpitrix.io/openpitrix/test/models"
)

// NewDeleteAttributesParams creates a new DeleteAttributesParams object
// with the default values initialized.
func NewDeleteAttributesParams() *DeleteAttributesParams {
	var ()
	return &DeleteAttributesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAttributesParamsWithTimeout creates a new DeleteAttributesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteAttributesParamsWithTimeout(timeout time.Duration) *DeleteAttributesParams {
	var ()
	return &DeleteAttributesParams{

		timeout: timeout,
	}
}

// NewDeleteAttributesParamsWithContext creates a new DeleteAttributesParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteAttributesParamsWithContext(ctx context.Context) *DeleteAttributesParams {
	var ()
	return &DeleteAttributesParams{

		Context: ctx,
	}
}

// NewDeleteAttributesParamsWithHTTPClient creates a new DeleteAttributesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteAttributesParamsWithHTTPClient(client *http.Client) *DeleteAttributesParams {
	var ()
	return &DeleteAttributesParams{
		HTTPClient: client,
	}
}

/*DeleteAttributesParams contains all the parameters to send to the API endpoint
for the delete attributes operation typically these are written to a http.Request
*/
type DeleteAttributesParams struct {

	/*Body*/
	Body *models.OpenpitrixDeleteAttributesRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete attributes params
func (o *DeleteAttributesParams) WithTimeout(timeout time.Duration) *DeleteAttributesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete attributes params
func (o *DeleteAttributesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete attributes params
func (o *DeleteAttributesParams) WithContext(ctx context.Context) *DeleteAttributesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete attributes params
func (o *DeleteAttributesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete attributes params
func (o *DeleteAttributesParams) WithHTTPClient(client *http.Client) *DeleteAttributesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete attributes params
func (o *DeleteAttributesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the delete attributes params
func (o *DeleteAttributesParams) WithBody(body *models.OpenpitrixDeleteAttributesRequest) *DeleteAttributesParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the delete attributes params
func (o *DeleteAttributesParams) SetBody(body *models.OpenpitrixDeleteAttributesRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAttributesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
