// Code generated by go-swagger; DO NOT EDIT.

package sku_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"openpitrix.io/openpitrix/test/models"
)

// NewDeleteSkusParams creates a new DeleteSkusParams object
// with the default values initialized.
func NewDeleteSkusParams() *DeleteSkusParams {
	var ()
	return &DeleteSkusParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteSkusParamsWithTimeout creates a new DeleteSkusParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteSkusParamsWithTimeout(timeout time.Duration) *DeleteSkusParams {
	var ()
	return &DeleteSkusParams{

		timeout: timeout,
	}
}

// NewDeleteSkusParamsWithContext creates a new DeleteSkusParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteSkusParamsWithContext(ctx context.Context) *DeleteSkusParams {
	var ()
	return &DeleteSkusParams{

		Context: ctx,
	}
}

// NewDeleteSkusParamsWithHTTPClient creates a new DeleteSkusParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteSkusParamsWithHTTPClient(client *http.Client) *DeleteSkusParams {
	var ()
	return &DeleteSkusParams{
		HTTPClient: client,
	}
}

/*DeleteSkusParams contains all the parameters to send to the API endpoint
for the delete skus operation typically these are written to a http.Request
*/
type DeleteSkusParams struct {

	/*Body*/
	Body *models.OpenpitrixDeleteSkusRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete skus params
func (o *DeleteSkusParams) WithTimeout(timeout time.Duration) *DeleteSkusParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete skus params
func (o *DeleteSkusParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete skus params
func (o *DeleteSkusParams) WithContext(ctx context.Context) *DeleteSkusParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete skus params
func (o *DeleteSkusParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete skus params
func (o *DeleteSkusParams) WithHTTPClient(client *http.Client) *DeleteSkusParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete skus params
func (o *DeleteSkusParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the delete skus params
func (o *DeleteSkusParams) WithBody(body *models.OpenpitrixDeleteSkusRequest) *DeleteSkusParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the delete skus params
func (o *DeleteSkusParams) SetBody(body *models.OpenpitrixDeleteSkusRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteSkusParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
