// Code generated by go-swagger; DO NOT EDIT.

package sku_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"openpitrix.io/openpitrix/test/models"
)

// DescribeSpusReader is a Reader for the DescribeSpus structure.
type DescribeSpusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DescribeSpusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDescribeSpusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDescribeSpusOK creates a DescribeSpusOK with default headers values
func NewDescribeSpusOK() *DescribeSpusOK {
	return &DescribeSpusOK{}
}

/*DescribeSpusOK handles this case with default header values.

A successful response.
*/
type DescribeSpusOK struct {
	Payload *models.OpenpitrixDescribeSpusResponse
}

func (o *DescribeSpusOK) Error() string {
	return fmt.Sprintf("[GET /v1/metering/spus][%d] describeSpusOK  %+v", 200, o.Payload)
}

func (o *DescribeSpusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OpenpitrixDescribeSpusResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
