// Code generated by go-swagger; DO NOT EDIT.

package sku_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDescribeAttributeNamesParams creates a new DescribeAttributeNamesParams object
// with the default values initialized.
func NewDescribeAttributeNamesParams() *DescribeAttributeNamesParams {
	var (
		typeVarDefault = string("NORMAL")
	)
	return &DescribeAttributeNamesParams{
		Type: &typeVarDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewDescribeAttributeNamesParamsWithTimeout creates a new DescribeAttributeNamesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDescribeAttributeNamesParamsWithTimeout(timeout time.Duration) *DescribeAttributeNamesParams {
	var (
		typeVarDefault = string("NORMAL")
	)
	return &DescribeAttributeNamesParams{
		Type: &typeVarDefault,

		timeout: timeout,
	}
}

// NewDescribeAttributeNamesParamsWithContext creates a new DescribeAttributeNamesParams object
// with the default values initialized, and the ability to set a context for a request
func NewDescribeAttributeNamesParamsWithContext(ctx context.Context) *DescribeAttributeNamesParams {
	var (
		typeDefault = string("NORMAL")
	)
	return &DescribeAttributeNamesParams{
		Type: &typeDefault,

		Context: ctx,
	}
}

// NewDescribeAttributeNamesParamsWithHTTPClient creates a new DescribeAttributeNamesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDescribeAttributeNamesParamsWithHTTPClient(client *http.Client) *DescribeAttributeNamesParams {
	var (
		typeDefault = string("NORMAL")
	)
	return &DescribeAttributeNamesParams{
		Type:       &typeDefault,
		HTTPClient: client,
	}
}

/*DescribeAttributeNamesParams contains all the parameters to send to the API endpoint
for the describe attribute names operation typically these are written to a http.Request
*/
type DescribeAttributeNamesParams struct {

	/*AttributeNameID*/
	AttributeNameID *string
	/*Limit*/
	Limit *int64
	/*Name*/
	Name *string
	/*Offset*/
	Offset *int64
	/*Reverse*/
	Reverse *bool
	/*SortKey*/
	SortKey *string
	/*Status*/
	Status *string
	/*Type*/
	Type *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the describe attribute names params
func (o *DescribeAttributeNamesParams) WithTimeout(timeout time.Duration) *DescribeAttributeNamesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the describe attribute names params
func (o *DescribeAttributeNamesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the describe attribute names params
func (o *DescribeAttributeNamesParams) WithContext(ctx context.Context) *DescribeAttributeNamesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the describe attribute names params
func (o *DescribeAttributeNamesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the describe attribute names params
func (o *DescribeAttributeNamesParams) WithHTTPClient(client *http.Client) *DescribeAttributeNamesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the describe attribute names params
func (o *DescribeAttributeNamesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAttributeNameID adds the attributeNameID to the describe attribute names params
func (o *DescribeAttributeNamesParams) WithAttributeNameID(attributeNameID *string) *DescribeAttributeNamesParams {
	o.SetAttributeNameID(attributeNameID)
	return o
}

// SetAttributeNameID adds the attributeNameId to the describe attribute names params
func (o *DescribeAttributeNamesParams) SetAttributeNameID(attributeNameID *string) {
	o.AttributeNameID = attributeNameID
}

// WithLimit adds the limit to the describe attribute names params
func (o *DescribeAttributeNamesParams) WithLimit(limit *int64) *DescribeAttributeNamesParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the describe attribute names params
func (o *DescribeAttributeNamesParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithName adds the name to the describe attribute names params
func (o *DescribeAttributeNamesParams) WithName(name *string) *DescribeAttributeNamesParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the describe attribute names params
func (o *DescribeAttributeNamesParams) SetName(name *string) {
	o.Name = name
}

// WithOffset adds the offset to the describe attribute names params
func (o *DescribeAttributeNamesParams) WithOffset(offset *int64) *DescribeAttributeNamesParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the describe attribute names params
func (o *DescribeAttributeNamesParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WithReverse adds the reverse to the describe attribute names params
func (o *DescribeAttributeNamesParams) WithReverse(reverse *bool) *DescribeAttributeNamesParams {
	o.SetReverse(reverse)
	return o
}

// SetReverse adds the reverse to the describe attribute names params
func (o *DescribeAttributeNamesParams) SetReverse(reverse *bool) {
	o.Reverse = reverse
}

// WithSortKey adds the sortKey to the describe attribute names params
func (o *DescribeAttributeNamesParams) WithSortKey(sortKey *string) *DescribeAttributeNamesParams {
	o.SetSortKey(sortKey)
	return o
}

// SetSortKey adds the sortKey to the describe attribute names params
func (o *DescribeAttributeNamesParams) SetSortKey(sortKey *string) {
	o.SortKey = sortKey
}

// WithStatus adds the status to the describe attribute names params
func (o *DescribeAttributeNamesParams) WithStatus(status *string) *DescribeAttributeNamesParams {
	o.SetStatus(status)
	return o
}

// SetStatus adds the status to the describe attribute names params
func (o *DescribeAttributeNamesParams) SetStatus(status *string) {
	o.Status = status
}

// WithType adds the typeVar to the describe attribute names params
func (o *DescribeAttributeNamesParams) WithType(typeVar *string) *DescribeAttributeNamesParams {
	o.SetType(typeVar)
	return o
}

// SetType adds the type to the describe attribute names params
func (o *DescribeAttributeNamesParams) SetType(typeVar *string) {
	o.Type = typeVar
}

// WriteToRequest writes these params to a swagger request
func (o *DescribeAttributeNamesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.AttributeNameID != nil {

		// query param attribute_name_id
		var qrAttributeNameID string
		if o.AttributeNameID != nil {
			qrAttributeNameID = *o.AttributeNameID
		}
		qAttributeNameID := qrAttributeNameID
		if qAttributeNameID != "" {
			if err := r.SetQueryParam("attribute_name_id", qAttributeNameID); err != nil {
				return err
			}
		}

	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.Name != nil {

		// query param name
		var qrName string
		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {
			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}

	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	if o.Reverse != nil {

		// query param reverse
		var qrReverse bool
		if o.Reverse != nil {
			qrReverse = *o.Reverse
		}
		qReverse := swag.FormatBool(qrReverse)
		if qReverse != "" {
			if err := r.SetQueryParam("reverse", qReverse); err != nil {
				return err
			}
		}

	}

	if o.SortKey != nil {

		// query param sort_key
		var qrSortKey string
		if o.SortKey != nil {
			qrSortKey = *o.SortKey
		}
		qSortKey := qrSortKey
		if qSortKey != "" {
			if err := r.SetQueryParam("sort_key", qSortKey); err != nil {
				return err
			}
		}

	}

	if o.Status != nil {

		// query param status
		var qrStatus string
		if o.Status != nil {
			qrStatus = *o.Status
		}
		qStatus := qrStatus
		if qStatus != "" {
			if err := r.SetQueryParam("status", qStatus); err != nil {
				return err
			}
		}

	}

	if o.Type != nil {

		// query param type
		var qrType string
		if o.Type != nil {
			qrType = *o.Type
		}
		qType := qrType
		if qType != "" {
			if err := r.SetQueryParam("type", qType); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
