// Code generated by go-swagger; DO NOT EDIT.

package sku_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDescribeAttributeUnitsParams creates a new DescribeAttributeUnitsParams object
// with the default values initialized.
func NewDescribeAttributeUnitsParams() *DescribeAttributeUnitsParams {
	var ()
	return &DescribeAttributeUnitsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDescribeAttributeUnitsParamsWithTimeout creates a new DescribeAttributeUnitsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDescribeAttributeUnitsParamsWithTimeout(timeout time.Duration) *DescribeAttributeUnitsParams {
	var ()
	return &DescribeAttributeUnitsParams{

		timeout: timeout,
	}
}

// NewDescribeAttributeUnitsParamsWithContext creates a new DescribeAttributeUnitsParams object
// with the default values initialized, and the ability to set a context for a request
func NewDescribeAttributeUnitsParamsWithContext(ctx context.Context) *DescribeAttributeUnitsParams {
	var ()
	return &DescribeAttributeUnitsParams{

		Context: ctx,
	}
}

// NewDescribeAttributeUnitsParamsWithHTTPClient creates a new DescribeAttributeUnitsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDescribeAttributeUnitsParamsWithHTTPClient(client *http.Client) *DescribeAttributeUnitsParams {
	var ()
	return &DescribeAttributeUnitsParams{
		HTTPClient: client,
	}
}

/*DescribeAttributeUnitsParams contains all the parameters to send to the API endpoint
for the describe attribute units operation typically these are written to a http.Request
*/
type DescribeAttributeUnitsParams struct {

	/*AttributeUnitID*/
	AttributeUnitID *string
	/*Limit*/
	Limit *int64
	/*Name*/
	Name *string
	/*Offset*/
	Offset *int64
	/*Reverse*/
	Reverse *bool
	/*SortKey*/
	SortKey *string
	/*Status*/
	Status *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the describe attribute units params
func (o *DescribeAttributeUnitsParams) WithTimeout(timeout time.Duration) *DescribeAttributeUnitsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the describe attribute units params
func (o *DescribeAttributeUnitsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the describe attribute units params
func (o *DescribeAttributeUnitsParams) WithContext(ctx context.Context) *DescribeAttributeUnitsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the describe attribute units params
func (o *DescribeAttributeUnitsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the describe attribute units params
func (o *DescribeAttributeUnitsParams) WithHTTPClient(client *http.Client) *DescribeAttributeUnitsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the describe attribute units params
func (o *DescribeAttributeUnitsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAttributeUnitID adds the attributeUnitID to the describe attribute units params
func (o *DescribeAttributeUnitsParams) WithAttributeUnitID(attributeUnitID *string) *DescribeAttributeUnitsParams {
	o.SetAttributeUnitID(attributeUnitID)
	return o
}

// SetAttributeUnitID adds the attributeUnitId to the describe attribute units params
func (o *DescribeAttributeUnitsParams) SetAttributeUnitID(attributeUnitID *string) {
	o.AttributeUnitID = attributeUnitID
}

// WithLimit adds the limit to the describe attribute units params
func (o *DescribeAttributeUnitsParams) WithLimit(limit *int64) *DescribeAttributeUnitsParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the describe attribute units params
func (o *DescribeAttributeUnitsParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithName adds the name to the describe attribute units params
func (o *DescribeAttributeUnitsParams) WithName(name *string) *DescribeAttributeUnitsParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the describe attribute units params
func (o *DescribeAttributeUnitsParams) SetName(name *string) {
	o.Name = name
}

// WithOffset adds the offset to the describe attribute units params
func (o *DescribeAttributeUnitsParams) WithOffset(offset *int64) *DescribeAttributeUnitsParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the describe attribute units params
func (o *DescribeAttributeUnitsParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WithReverse adds the reverse to the describe attribute units params
func (o *DescribeAttributeUnitsParams) WithReverse(reverse *bool) *DescribeAttributeUnitsParams {
	o.SetReverse(reverse)
	return o
}

// SetReverse adds the reverse to the describe attribute units params
func (o *DescribeAttributeUnitsParams) SetReverse(reverse *bool) {
	o.Reverse = reverse
}

// WithSortKey adds the sortKey to the describe attribute units params
func (o *DescribeAttributeUnitsParams) WithSortKey(sortKey *string) *DescribeAttributeUnitsParams {
	o.SetSortKey(sortKey)
	return o
}

// SetSortKey adds the sortKey to the describe attribute units params
func (o *DescribeAttributeUnitsParams) SetSortKey(sortKey *string) {
	o.SortKey = sortKey
}

// WithStatus adds the status to the describe attribute units params
func (o *DescribeAttributeUnitsParams) WithStatus(status *string) *DescribeAttributeUnitsParams {
	o.SetStatus(status)
	return o
}

// SetStatus adds the status to the describe attribute units params
func (o *DescribeAttributeUnitsParams) SetStatus(status *string) {
	o.Status = status
}

// WriteToRequest writes these params to a swagger request
func (o *DescribeAttributeUnitsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.AttributeUnitID != nil {

		// query param attribute_unit_id
		var qrAttributeUnitID string
		if o.AttributeUnitID != nil {
			qrAttributeUnitID = *o.AttributeUnitID
		}
		qAttributeUnitID := qrAttributeUnitID
		if qAttributeUnitID != "" {
			if err := r.SetQueryParam("attribute_unit_id", qAttributeUnitID); err != nil {
				return err
			}
		}

	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.Name != nil {

		// query param name
		var qrName string
		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {
			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}

	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	if o.Reverse != nil {

		// query param reverse
		var qrReverse bool
		if o.Reverse != nil {
			qrReverse = *o.Reverse
		}
		qReverse := swag.FormatBool(qrReverse)
		if qReverse != "" {
			if err := r.SetQueryParam("reverse", qReverse); err != nil {
				return err
			}
		}

	}

	if o.SortKey != nil {

		// query param sort_key
		var qrSortKey string
		if o.SortKey != nil {
			qrSortKey = *o.SortKey
		}
		qSortKey := qrSortKey
		if qSortKey != "" {
			if err := r.SetQueryParam("sort_key", qSortKey); err != nil {
				return err
			}
		}

	}

	if o.Status != nil {

		// query param status
		var qrStatus string
		if o.Status != nil {
			qrStatus = *o.Status
		}
		qStatus := qrStatus
		if qStatus != "" {
			if err := r.SetQueryParam("status", qStatus); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
