// Code generated by go-swagger; DO NOT EDIT.

package sku_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"openpitrix.io/openpitrix/test/models"
)

// ModifySkuReader is a Reader for the ModifySku structure.
type ModifySkuReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ModifySkuReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewModifySkuOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewModifySkuOK creates a ModifySkuOK with default headers values
func NewModifySkuOK() *ModifySkuOK {
	return &ModifySkuOK{}
}

/*ModifySkuOK handles this case with default header values.

A successful response.
*/
type ModifySkuOK struct {
	Payload *models.OpenpitrixModifySkuResponse
}

func (o *ModifySkuOK) Error() string {
	return fmt.Sprintf("[PUT /v1/metering/sku][%d] modifySkuOK  %+v", 200, o.Payload)
}

func (o *ModifySkuOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OpenpitrixModifySkuResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
