// Code generated by go-swagger; DO NOT EDIT.

package sku_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"openpitrix.io/openpitrix/test/models"
)

// NewModifyAttributeNameParams creates a new ModifyAttributeNameParams object
// with the default values initialized.
func NewModifyAttributeNameParams() *ModifyAttributeNameParams {
	var ()
	return &ModifyAttributeNameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewModifyAttributeNameParamsWithTimeout creates a new ModifyAttributeNameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewModifyAttributeNameParamsWithTimeout(timeout time.Duration) *ModifyAttributeNameParams {
	var ()
	return &ModifyAttributeNameParams{

		timeout: timeout,
	}
}

// NewModifyAttributeNameParamsWithContext creates a new ModifyAttributeNameParams object
// with the default values initialized, and the ability to set a context for a request
func NewModifyAttributeNameParamsWithContext(ctx context.Context) *ModifyAttributeNameParams {
	var ()
	return &ModifyAttributeNameParams{

		Context: ctx,
	}
}

// NewModifyAttributeNameParamsWithHTTPClient creates a new ModifyAttributeNameParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewModifyAttributeNameParamsWithHTTPClient(client *http.Client) *ModifyAttributeNameParams {
	var ()
	return &ModifyAttributeNameParams{
		HTTPClient: client,
	}
}

/*ModifyAttributeNameParams contains all the parameters to send to the API endpoint
for the modify attribute name operation typically these are written to a http.Request
*/
type ModifyAttributeNameParams struct {

	/*Body*/
	Body *models.OpenpitrixModifyAttributeNameRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the modify attribute name params
func (o *ModifyAttributeNameParams) WithTimeout(timeout time.Duration) *ModifyAttributeNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the modify attribute name params
func (o *ModifyAttributeNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the modify attribute name params
func (o *ModifyAttributeNameParams) WithContext(ctx context.Context) *ModifyAttributeNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the modify attribute name params
func (o *ModifyAttributeNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the modify attribute name params
func (o *ModifyAttributeNameParams) WithHTTPClient(client *http.Client) *ModifyAttributeNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the modify attribute name params
func (o *ModifyAttributeNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the modify attribute name params
func (o *ModifyAttributeNameParams) WithBody(body *models.OpenpitrixModifyAttributeNameRequest) *ModifyAttributeNameParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the modify attribute name params
func (o *ModifyAttributeNameParams) SetBody(body *models.OpenpitrixModifyAttributeNameRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ModifyAttributeNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
