// Code generated by go-swagger; DO NOT EDIT.

package sku_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"openpitrix.io/openpitrix/test/models"
)

// NewModifySkuParams creates a new ModifySkuParams object
// with the default values initialized.
func NewModifySkuParams() *ModifySkuParams {
	var ()
	return &ModifySkuParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewModifySkuParamsWithTimeout creates a new ModifySkuParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewModifySkuParamsWithTimeout(timeout time.Duration) *ModifySkuParams {
	var ()
	return &ModifySkuParams{

		timeout: timeout,
	}
}

// NewModifySkuParamsWithContext creates a new ModifySkuParams object
// with the default values initialized, and the ability to set a context for a request
func NewModifySkuParamsWithContext(ctx context.Context) *ModifySkuParams {
	var ()
	return &ModifySkuParams{

		Context: ctx,
	}
}

// NewModifySkuParamsWithHTTPClient creates a new ModifySkuParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewModifySkuParamsWithHTTPClient(client *http.Client) *ModifySkuParams {
	var ()
	return &ModifySkuParams{
		HTTPClient: client,
	}
}

/*ModifySkuParams contains all the parameters to send to the API endpoint
for the modify sku operation typically these are written to a http.Request
*/
type ModifySkuParams struct {

	/*Body*/
	Body *models.OpenpitrixModifySkuRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the modify sku params
func (o *ModifySkuParams) WithTimeout(timeout time.Duration) *ModifySkuParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the modify sku params
func (o *ModifySkuParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the modify sku params
func (o *ModifySkuParams) WithContext(ctx context.Context) *ModifySkuParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the modify sku params
func (o *ModifySkuParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the modify sku params
func (o *ModifySkuParams) WithHTTPClient(client *http.Client) *ModifySkuParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the modify sku params
func (o *ModifySkuParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the modify sku params
func (o *ModifySkuParams) WithBody(body *models.OpenpitrixModifySkuRequest) *ModifySkuParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the modify sku params
func (o *ModifySkuParams) SetBody(body *models.OpenpitrixModifySkuRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ModifySkuParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
