// Code generated by go-swagger; DO NOT EDIT.

package sku_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"openpitrix.io/openpitrix/test/models"
)

// NewModifySpuParams creates a new ModifySpuParams object
// with the default values initialized.
func NewModifySpuParams() *ModifySpuParams {
	var ()
	return &ModifySpuParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewModifySpuParamsWithTimeout creates a new ModifySpuParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewModifySpuParamsWithTimeout(timeout time.Duration) *ModifySpuParams {
	var ()
	return &ModifySpuParams{

		timeout: timeout,
	}
}

// NewModifySpuParamsWithContext creates a new ModifySpuParams object
// with the default values initialized, and the ability to set a context for a request
func NewModifySpuParamsWithContext(ctx context.Context) *ModifySpuParams {
	var ()
	return &ModifySpuParams{

		Context: ctx,
	}
}

// NewModifySpuParamsWithHTTPClient creates a new ModifySpuParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewModifySpuParamsWithHTTPClient(client *http.Client) *ModifySpuParams {
	var ()
	return &ModifySpuParams{
		HTTPClient: client,
	}
}

/*ModifySpuParams contains all the parameters to send to the API endpoint
for the modify spu operation typically these are written to a http.Request
*/
type ModifySpuParams struct {

	/*Body*/
	Body *models.OpenpitrixModifySpuRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the modify spu params
func (o *ModifySpuParams) WithTimeout(timeout time.Duration) *ModifySpuParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the modify spu params
func (o *ModifySpuParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the modify spu params
func (o *ModifySpuParams) WithContext(ctx context.Context) *ModifySpuParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the modify spu params
func (o *ModifySpuParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the modify spu params
func (o *ModifySpuParams) WithHTTPClient(client *http.Client) *ModifySpuParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the modify spu params
func (o *ModifySpuParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the modify spu params
func (o *ModifySpuParams) WithBody(body *models.OpenpitrixModifySpuRequest) *ModifySpuParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the modify spu params
func (o *ModifySpuParams) SetBody(body *models.OpenpitrixModifySpuRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ModifySpuParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
