// Code generated by go-swagger; DO NOT EDIT.

package billing_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"openpitrix.io/openpitrix/test/models"
)

// CreateRechargeReader is a Reader for the CreateRecharge structure.
type CreateRechargeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateRechargeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCreateRechargeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateRechargeOK creates a CreateRechargeOK with default headers values
func NewCreateRechargeOK() *CreateRechargeOK {
	return &CreateRechargeOK{}
}

/*CreateRechargeOK handles this case with default header values.

A successful response.
*/
type CreateRechargeOK struct {
	Payload *models.OpenpitrixCreateRechargeResponse
}

func (o *CreateRechargeOK) Error() string {
	return fmt.Sprintf("[POST /v1/billing/recharge][%d] createRechargeOK  %+v", 200, o.Payload)
}

func (o *CreateRechargeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OpenpitrixCreateRechargeResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
