// Code generated by go-swagger; DO NOT EDIT.

package billing_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"openpitrix.io/openpitrix/test/models"
)

// CreateWithdrawReader is a Reader for the CreateWithdraw structure.
type CreateWithdrawReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateWithdrawReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCreateWithdrawOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateWithdrawOK creates a CreateWithdrawOK with default headers values
func NewCreateWithdrawOK() *CreateWithdrawOK {
	return &CreateWithdrawOK{}
}

/*CreateWithdrawOK handles this case with default header values.

A successful response.
*/
type CreateWithdrawOK struct {
	Payload *models.OpenpitrixCreateWithdrawResponse
}

func (o *CreateWithdrawOK) Error() string {
	return fmt.Sprintf("[POST /v1/billing/withdraw][%d] createWithdrawOK  %+v", 200, o.Payload)
}

func (o *CreateWithdrawOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OpenpitrixCreateWithdrawResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
