// Code generated by go-swagger; DO NOT EDIT.

package billing_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDescribeLeasedContractsParams creates a new DescribeLeasedContractsParams object
// with the default values initialized.
func NewDescribeLeasedContractsParams() *DescribeLeasedContractsParams {
	var ()
	return &DescribeLeasedContractsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDescribeLeasedContractsParamsWithTimeout creates a new DescribeLeasedContractsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDescribeLeasedContractsParamsWithTimeout(timeout time.Duration) *DescribeLeasedContractsParams {
	var ()
	return &DescribeLeasedContractsParams{

		timeout: timeout,
	}
}

// NewDescribeLeasedContractsParamsWithContext creates a new DescribeLeasedContractsParams object
// with the default values initialized, and the ability to set a context for a request
func NewDescribeLeasedContractsParamsWithContext(ctx context.Context) *DescribeLeasedContractsParams {
	var ()
	return &DescribeLeasedContractsParams{

		Context: ctx,
	}
}

// NewDescribeLeasedContractsParamsWithHTTPClient creates a new DescribeLeasedContractsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDescribeLeasedContractsParamsWithHTTPClient(client *http.Client) *DescribeLeasedContractsParams {
	var ()
	return &DescribeLeasedContractsParams{
		HTTPClient: client,
	}
}

/*DescribeLeasedContractsParams contains all the parameters to send to the API endpoint
for the describe leased contracts operation typically these are written to a http.Request
*/
type DescribeLeasedContractsParams struct {

	/*ContractID*/
	ContractID *string
	/*LeasingID*/
	LeasingID *string
	/*Limit*/
	Limit *int64
	/*Offset*/
	Offset *int64
	/*ResourceID*/
	ResourceID *string
	/*Reverse*/
	Reverse *bool
	/*SkuID*/
	SkuID *string
	/*SortKey*/
	SortKey *string
	/*Status*/
	Status *string
	/*UserID*/
	UserID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the describe leased contracts params
func (o *DescribeLeasedContractsParams) WithTimeout(timeout time.Duration) *DescribeLeasedContractsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the describe leased contracts params
func (o *DescribeLeasedContractsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the describe leased contracts params
func (o *DescribeLeasedContractsParams) WithContext(ctx context.Context) *DescribeLeasedContractsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the describe leased contracts params
func (o *DescribeLeasedContractsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the describe leased contracts params
func (o *DescribeLeasedContractsParams) WithHTTPClient(client *http.Client) *DescribeLeasedContractsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the describe leased contracts params
func (o *DescribeLeasedContractsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithContractID adds the contractID to the describe leased contracts params
func (o *DescribeLeasedContractsParams) WithContractID(contractID *string) *DescribeLeasedContractsParams {
	o.SetContractID(contractID)
	return o
}

// SetContractID adds the contractId to the describe leased contracts params
func (o *DescribeLeasedContractsParams) SetContractID(contractID *string) {
	o.ContractID = contractID
}

// WithLeasingID adds the leasingID to the describe leased contracts params
func (o *DescribeLeasedContractsParams) WithLeasingID(leasingID *string) *DescribeLeasedContractsParams {
	o.SetLeasingID(leasingID)
	return o
}

// SetLeasingID adds the leasingId to the describe leased contracts params
func (o *DescribeLeasedContractsParams) SetLeasingID(leasingID *string) {
	o.LeasingID = leasingID
}

// WithLimit adds the limit to the describe leased contracts params
func (o *DescribeLeasedContractsParams) WithLimit(limit *int64) *DescribeLeasedContractsParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the describe leased contracts params
func (o *DescribeLeasedContractsParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithOffset adds the offset to the describe leased contracts params
func (o *DescribeLeasedContractsParams) WithOffset(offset *int64) *DescribeLeasedContractsParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the describe leased contracts params
func (o *DescribeLeasedContractsParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WithResourceID adds the resourceID to the describe leased contracts params
func (o *DescribeLeasedContractsParams) WithResourceID(resourceID *string) *DescribeLeasedContractsParams {
	o.SetResourceID(resourceID)
	return o
}

// SetResourceID adds the resourceId to the describe leased contracts params
func (o *DescribeLeasedContractsParams) SetResourceID(resourceID *string) {
	o.ResourceID = resourceID
}

// WithReverse adds the reverse to the describe leased contracts params
func (o *DescribeLeasedContractsParams) WithReverse(reverse *bool) *DescribeLeasedContractsParams {
	o.SetReverse(reverse)
	return o
}

// SetReverse adds the reverse to the describe leased contracts params
func (o *DescribeLeasedContractsParams) SetReverse(reverse *bool) {
	o.Reverse = reverse
}

// WithSkuID adds the skuID to the describe leased contracts params
func (o *DescribeLeasedContractsParams) WithSkuID(skuID *string) *DescribeLeasedContractsParams {
	o.SetSkuID(skuID)
	return o
}

// SetSkuID adds the skuId to the describe leased contracts params
func (o *DescribeLeasedContractsParams) SetSkuID(skuID *string) {
	o.SkuID = skuID
}

// WithSortKey adds the sortKey to the describe leased contracts params
func (o *DescribeLeasedContractsParams) WithSortKey(sortKey *string) *DescribeLeasedContractsParams {
	o.SetSortKey(sortKey)
	return o
}

// SetSortKey adds the sortKey to the describe leased contracts params
func (o *DescribeLeasedContractsParams) SetSortKey(sortKey *string) {
	o.SortKey = sortKey
}

// WithStatus adds the status to the describe leased contracts params
func (o *DescribeLeasedContractsParams) WithStatus(status *string) *DescribeLeasedContractsParams {
	o.SetStatus(status)
	return o
}

// SetStatus adds the status to the describe leased contracts params
func (o *DescribeLeasedContractsParams) SetStatus(status *string) {
	o.Status = status
}

// WithUserID adds the userID to the describe leased contracts params
func (o *DescribeLeasedContractsParams) WithUserID(userID *string) *DescribeLeasedContractsParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the describe leased contracts params
func (o *DescribeLeasedContractsParams) SetUserID(userID *string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *DescribeLeasedContractsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ContractID != nil {

		// query param contract_id
		var qrContractID string
		if o.ContractID != nil {
			qrContractID = *o.ContractID
		}
		qContractID := qrContractID
		if qContractID != "" {
			if err := r.SetQueryParam("contract_id", qContractID); err != nil {
				return err
			}
		}

	}

	if o.LeasingID != nil {

		// query param leasing_id
		var qrLeasingID string
		if o.LeasingID != nil {
			qrLeasingID = *o.LeasingID
		}
		qLeasingID := qrLeasingID
		if qLeasingID != "" {
			if err := r.SetQueryParam("leasing_id", qLeasingID); err != nil {
				return err
			}
		}

	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	if o.ResourceID != nil {

		// query param resource_id
		var qrResourceID string
		if o.ResourceID != nil {
			qrResourceID = *o.ResourceID
		}
		qResourceID := qrResourceID
		if qResourceID != "" {
			if err := r.SetQueryParam("resource_id", qResourceID); err != nil {
				return err
			}
		}

	}

	if o.Reverse != nil {

		// query param reverse
		var qrReverse bool
		if o.Reverse != nil {
			qrReverse = *o.Reverse
		}
		qReverse := swag.FormatBool(qrReverse)
		if qReverse != "" {
			if err := r.SetQueryParam("reverse", qReverse); err != nil {
				return err
			}
		}

	}

	if o.SkuID != nil {

		// query param sku_id
		var qrSkuID string
		if o.SkuID != nil {
			qrSkuID = *o.SkuID
		}
		qSkuID := qrSkuID
		if qSkuID != "" {
			if err := r.SetQueryParam("sku_id", qSkuID); err != nil {
				return err
			}
		}

	}

	if o.SortKey != nil {

		// query param sort_key
		var qrSortKey string
		if o.SortKey != nil {
			qrSortKey = *o.SortKey
		}
		qSortKey := qrSortKey
		if qSortKey != "" {
			if err := r.SetQueryParam("sort_key", qSortKey); err != nil {
				return err
			}
		}

	}

	if o.Status != nil {

		// query param status
		var qrStatus string
		if o.Status != nil {
			qrStatus = *o.Status
		}
		qStatus := qrStatus
		if qStatus != "" {
			if err := r.SetQueryParam("status", qStatus); err != nil {
				return err
			}
		}

	}

	if o.UserID != nil {

		// query param user_id
		var qrUserID string
		if o.UserID != nil {
			qrUserID = *o.UserID
		}
		qUserID := qrUserID
		if qUserID != "" {
			if err := r.SetQueryParam("user_id", qUserID); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
