// Code generated by go-swagger; DO NOT EDIT.

package billing_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"openpitrix.io/openpitrix/test/models"
)

// DescribeLeasingContractsReader is a Reader for the DescribeLeasingContracts structure.
type DescribeLeasingContractsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DescribeLeasingContractsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDescribeLeasingContractsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDescribeLeasingContractsOK creates a DescribeLeasingContractsOK with default headers values
func NewDescribeLeasingContractsOK() *DescribeLeasingContractsOK {
	return &DescribeLeasingContractsOK{}
}

/*DescribeLeasingContractsOK handles this case with default header values.

A successful response.
*/
type DescribeLeasingContractsOK struct {
	Payload *models.OpenpitrixDescribeLeasingContractsResponse
}

func (o *DescribeLeasingContractsOK) Error() string {
	return fmt.Sprintf("[GET /v1/billing/leasing/contracts][%d] describeLeasingContractsOK  %+v", 200, o.Payload)
}

func (o *DescribeLeasingContractsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OpenpitrixDescribeLeasingContractsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
