// Code generated by go-swagger; DO NOT EDIT.

package billing_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"openpitrix.io/openpitrix/test/models"
)

// DescribeChargesReader is a Reader for the DescribeCharges structure.
type DescribeChargesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DescribeChargesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDescribeChargesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDescribeChargesOK creates a DescribeChargesOK with default headers values
func NewDescribeChargesOK() *DescribeChargesOK {
	return &DescribeChargesOK{}
}

/*DescribeChargesOK handles this case with default header values.

A successful response.
*/
type DescribeChargesOK struct {
	Payload *models.OpenpitrixDescribeChargesResponse
}

func (o *DescribeChargesOK) Error() string {
	return fmt.Sprintf("[GET /v1/billing/charges][%d] describeChargesOK  %+v", 200, o.Payload)
}

func (o *DescribeChargesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OpenpitrixDescribeChargesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
