// Code generated by go-swagger; DO NOT EDIT.

package billing_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDescribeChargesParams creates a new DescribeChargesParams object
// with the default values initialized.
func NewDescribeChargesParams() *DescribeChargesParams {
	var ()
	return &DescribeChargesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDescribeChargesParamsWithTimeout creates a new DescribeChargesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDescribeChargesParamsWithTimeout(timeout time.Duration) *DescribeChargesParams {
	var ()
	return &DescribeChargesParams{

		timeout: timeout,
	}
}

// NewDescribeChargesParamsWithContext creates a new DescribeChargesParams object
// with the default values initialized, and the ability to set a context for a request
func NewDescribeChargesParamsWithContext(ctx context.Context) *DescribeChargesParams {
	var ()
	return &DescribeChargesParams{

		Context: ctx,
	}
}

// NewDescribeChargesParamsWithHTTPClient creates a new DescribeChargesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDescribeChargesParamsWithHTTPClient(client *http.Client) *DescribeChargesParams {
	var ()
	return &DescribeChargesParams{
		HTTPClient: client,
	}
}

/*DescribeChargesParams contains all the parameters to send to the API endpoint
for the describe charges operation typically these are written to a http.Request
*/
type DescribeChargesParams struct {

	/*ChargeID*/
	ChargeID *string
	/*ContractID*/
	ContractID *string
	/*Limit*/
	Limit *int64
	/*Offset*/
	Offset *int64
	/*Reverse*/
	Reverse *bool
	/*SortKey*/
	SortKey *string
	/*UserID*/
	UserID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the describe charges params
func (o *DescribeChargesParams) WithTimeout(timeout time.Duration) *DescribeChargesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the describe charges params
func (o *DescribeChargesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the describe charges params
func (o *DescribeChargesParams) WithContext(ctx context.Context) *DescribeChargesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the describe charges params
func (o *DescribeChargesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the describe charges params
func (o *DescribeChargesParams) WithHTTPClient(client *http.Client) *DescribeChargesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the describe charges params
func (o *DescribeChargesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithChargeID adds the chargeID to the describe charges params
func (o *DescribeChargesParams) WithChargeID(chargeID *string) *DescribeChargesParams {
	o.SetChargeID(chargeID)
	return o
}

// SetChargeID adds the chargeId to the describe charges params
func (o *DescribeChargesParams) SetChargeID(chargeID *string) {
	o.ChargeID = chargeID
}

// WithContractID adds the contractID to the describe charges params
func (o *DescribeChargesParams) WithContractID(contractID *string) *DescribeChargesParams {
	o.SetContractID(contractID)
	return o
}

// SetContractID adds the contractId to the describe charges params
func (o *DescribeChargesParams) SetContractID(contractID *string) {
	o.ContractID = contractID
}

// WithLimit adds the limit to the describe charges params
func (o *DescribeChargesParams) WithLimit(limit *int64) *DescribeChargesParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the describe charges params
func (o *DescribeChargesParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithOffset adds the offset to the describe charges params
func (o *DescribeChargesParams) WithOffset(offset *int64) *DescribeChargesParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the describe charges params
func (o *DescribeChargesParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WithReverse adds the reverse to the describe charges params
func (o *DescribeChargesParams) WithReverse(reverse *bool) *DescribeChargesParams {
	o.SetReverse(reverse)
	return o
}

// SetReverse adds the reverse to the describe charges params
func (o *DescribeChargesParams) SetReverse(reverse *bool) {
	o.Reverse = reverse
}

// WithSortKey adds the sortKey to the describe charges params
func (o *DescribeChargesParams) WithSortKey(sortKey *string) *DescribeChargesParams {
	o.SetSortKey(sortKey)
	return o
}

// SetSortKey adds the sortKey to the describe charges params
func (o *DescribeChargesParams) SetSortKey(sortKey *string) {
	o.SortKey = sortKey
}

// WithUserID adds the userID to the describe charges params
func (o *DescribeChargesParams) WithUserID(userID *string) *DescribeChargesParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the describe charges params
func (o *DescribeChargesParams) SetUserID(userID *string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *DescribeChargesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ChargeID != nil {

		// query param charge_id
		var qrChargeID string
		if o.ChargeID != nil {
			qrChargeID = *o.ChargeID
		}
		qChargeID := qrChargeID
		if qChargeID != "" {
			if err := r.SetQueryParam("charge_id", qChargeID); err != nil {
				return err
			}
		}

	}

	if o.ContractID != nil {

		// query param contract_id
		var qrContractID string
		if o.ContractID != nil {
			qrContractID = *o.ContractID
		}
		qContractID := qrContractID
		if qContractID != "" {
			if err := r.SetQueryParam("contract_id", qContractID); err != nil {
				return err
			}
		}

	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	if o.Reverse != nil {

		// query param reverse
		var qrReverse bool
		if o.Reverse != nil {
			qrReverse = *o.Reverse
		}
		qReverse := swag.FormatBool(qrReverse)
		if qReverse != "" {
			if err := r.SetQueryParam("reverse", qReverse); err != nil {
				return err
			}
		}

	}

	if o.SortKey != nil {

		// query param sort_key
		var qrSortKey string
		if o.SortKey != nil {
			qrSortKey = *o.SortKey
		}
		qSortKey := qrSortKey
		if qSortKey != "" {
			if err := r.SetQueryParam("sort_key", qSortKey); err != nil {
				return err
			}
		}

	}

	if o.UserID != nil {

		// query param user_id
		var qrUserID string
		if o.UserID != nil {
			qrUserID = *o.UserID
		}
		qUserID := qrUserID
		if qUserID != "" {
			if err := r.SetQueryParam("user_id", qUserID); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
