// Code generated by go-swagger; DO NOT EDIT.

package billing_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"openpitrix.io/openpitrix/test/models"
)

// ModifyPriceReader is a Reader for the ModifyPrice structure.
type ModifyPriceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ModifyPriceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewModifyPriceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewModifyPriceOK creates a ModifyPriceOK with default headers values
func NewModifyPriceOK() *ModifyPriceOK {
	return &ModifyPriceOK{}
}

/*ModifyPriceOK handles this case with default header values.

A successful response.
*/
type ModifyPriceOK struct {
	Payload *models.OpenpitrixModifyPriceResponse
}

func (o *ModifyPriceOK) Error() string {
	return fmt.Sprintf("[PUT /v1/billing/price][%d] modifyPriceOK  %+v", 200, o.Payload)
}

func (o *ModifyPriceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OpenpitrixModifyPriceResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
