// Code generated by go-swagger; DO NOT EDIT.

package promotion_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"openpitrix.io/openpitrix/test/models"
)

// NewCreateCombinationPriceParams creates a new CreateCombinationPriceParams object
// with the default values initialized.
func NewCreateCombinationPriceParams() *CreateCombinationPriceParams {
	var ()
	return &CreateCombinationPriceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateCombinationPriceParamsWithTimeout creates a new CreateCombinationPriceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateCombinationPriceParamsWithTimeout(timeout time.Duration) *CreateCombinationPriceParams {
	var ()
	return &CreateCombinationPriceParams{

		timeout: timeout,
	}
}

// NewCreateCombinationPriceParamsWithContext creates a new CreateCombinationPriceParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateCombinationPriceParamsWithContext(ctx context.Context) *CreateCombinationPriceParams {
	var ()
	return &CreateCombinationPriceParams{

		Context: ctx,
	}
}

// NewCreateCombinationPriceParamsWithHTTPClient creates a new CreateCombinationPriceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateCombinationPriceParamsWithHTTPClient(client *http.Client) *CreateCombinationPriceParams {
	var ()
	return &CreateCombinationPriceParams{
		HTTPClient: client,
	}
}

/*CreateCombinationPriceParams contains all the parameters to send to the API endpoint
for the create combination price operation typically these are written to a http.Request
*/
type CreateCombinationPriceParams struct {

	/*Body*/
	Body *models.OpenpitrixCreateCombinationPriceRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create combination price params
func (o *CreateCombinationPriceParams) WithTimeout(timeout time.Duration) *CreateCombinationPriceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create combination price params
func (o *CreateCombinationPriceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create combination price params
func (o *CreateCombinationPriceParams) WithContext(ctx context.Context) *CreateCombinationPriceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create combination price params
func (o *CreateCombinationPriceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create combination price params
func (o *CreateCombinationPriceParams) WithHTTPClient(client *http.Client) *CreateCombinationPriceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create combination price params
func (o *CreateCombinationPriceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create combination price params
func (o *CreateCombinationPriceParams) WithBody(body *models.OpenpitrixCreateCombinationPriceRequest) *CreateCombinationPriceParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create combination price params
func (o *CreateCombinationPriceParams) SetBody(body *models.OpenpitrixCreateCombinationPriceRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateCombinationPriceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
