// Code generated by go-swagger; DO NOT EDIT.

package promotion_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"openpitrix.io/openpitrix/test/models"
)

// CreateCouponReceivedReader is a Reader for the CreateCouponReceived structure.
type CreateCouponReceivedReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateCouponReceivedReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCreateCouponReceivedOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateCouponReceivedOK creates a CreateCouponReceivedOK with default headers values
func NewCreateCouponReceivedOK() *CreateCouponReceivedOK {
	return &CreateCouponReceivedOK{}
}

/*CreateCouponReceivedOK handles this case with default header values.

A successful response.
*/
type CreateCouponReceivedOK struct {
	Payload *models.OpenpitrixCreateCouponReceivedResponse
}

func (o *CreateCouponReceivedOK) Error() string {
	return fmt.Sprintf("[POST /v1/billing/coupon/received][%d] createCouponReceivedOK  %+v", 200, o.Payload)
}

func (o *CreateCouponReceivedOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OpenpitrixCreateCouponReceivedResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
