// Code generated by go-swagger; DO NOT EDIT.

package promotion_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"openpitrix.io/openpitrix/test/models"
)

// NewCreateCouponReceivedParams creates a new CreateCouponReceivedParams object
// with the default values initialized.
func NewCreateCouponReceivedParams() *CreateCouponReceivedParams {
	var ()
	return &CreateCouponReceivedParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateCouponReceivedParamsWithTimeout creates a new CreateCouponReceivedParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateCouponReceivedParamsWithTimeout(timeout time.Duration) *CreateCouponReceivedParams {
	var ()
	return &CreateCouponReceivedParams{

		timeout: timeout,
	}
}

// NewCreateCouponReceivedParamsWithContext creates a new CreateCouponReceivedParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateCouponReceivedParamsWithContext(ctx context.Context) *CreateCouponReceivedParams {
	var ()
	return &CreateCouponReceivedParams{

		Context: ctx,
	}
}

// NewCreateCouponReceivedParamsWithHTTPClient creates a new CreateCouponReceivedParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateCouponReceivedParamsWithHTTPClient(client *http.Client) *CreateCouponReceivedParams {
	var ()
	return &CreateCouponReceivedParams{
		HTTPClient: client,
	}
}

/*CreateCouponReceivedParams contains all the parameters to send to the API endpoint
for the create coupon received operation typically these are written to a http.Request
*/
type CreateCouponReceivedParams struct {

	/*Body*/
	Body *models.OpenpitrixCreateCouponReceivedRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create coupon received params
func (o *CreateCouponReceivedParams) WithTimeout(timeout time.Duration) *CreateCouponReceivedParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create coupon received params
func (o *CreateCouponReceivedParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create coupon received params
func (o *CreateCouponReceivedParams) WithContext(ctx context.Context) *CreateCouponReceivedParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create coupon received params
func (o *CreateCouponReceivedParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create coupon received params
func (o *CreateCouponReceivedParams) WithHTTPClient(client *http.Client) *CreateCouponReceivedParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create coupon received params
func (o *CreateCouponReceivedParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create coupon received params
func (o *CreateCouponReceivedParams) WithBody(body *models.OpenpitrixCreateCouponReceivedRequest) *CreateCouponReceivedParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create coupon received params
func (o *CreateCouponReceivedParams) SetBody(body *models.OpenpitrixCreateCouponReceivedRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateCouponReceivedParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
