// Code generated by go-swagger; DO NOT EDIT.

package promotion_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"openpitrix.io/openpitrix/test/models"
)

// NewDeleteCouponsParams creates a new DeleteCouponsParams object
// with the default values initialized.
func NewDeleteCouponsParams() *DeleteCouponsParams {
	var ()
	return &DeleteCouponsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteCouponsParamsWithTimeout creates a new DeleteCouponsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteCouponsParamsWithTimeout(timeout time.Duration) *DeleteCouponsParams {
	var ()
	return &DeleteCouponsParams{

		timeout: timeout,
	}
}

// NewDeleteCouponsParamsWithContext creates a new DeleteCouponsParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteCouponsParamsWithContext(ctx context.Context) *DeleteCouponsParams {
	var ()
	return &DeleteCouponsParams{

		Context: ctx,
	}
}

// NewDeleteCouponsParamsWithHTTPClient creates a new DeleteCouponsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteCouponsParamsWithHTTPClient(client *http.Client) *DeleteCouponsParams {
	var ()
	return &DeleteCouponsParams{
		HTTPClient: client,
	}
}

/*DeleteCouponsParams contains all the parameters to send to the API endpoint
for the delete coupons operation typically these are written to a http.Request
*/
type DeleteCouponsParams struct {

	/*Body*/
	Body *models.OpenpitrixDeleteCouponsRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete coupons params
func (o *DeleteCouponsParams) WithTimeout(timeout time.Duration) *DeleteCouponsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete coupons params
func (o *DeleteCouponsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete coupons params
func (o *DeleteCouponsParams) WithContext(ctx context.Context) *DeleteCouponsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete coupons params
func (o *DeleteCouponsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete coupons params
func (o *DeleteCouponsParams) WithHTTPClient(client *http.Client) *DeleteCouponsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete coupons params
func (o *DeleteCouponsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the delete coupons params
func (o *DeleteCouponsParams) WithBody(body *models.OpenpitrixDeleteCouponsRequest) *DeleteCouponsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the delete coupons params
func (o *DeleteCouponsParams) SetBody(body *models.OpenpitrixDeleteCouponsRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteCouponsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
