// Code generated by go-swagger; DO NOT EDIT.

package promotion_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"openpitrix.io/openpitrix/test/models"
)

// NewDeleteDiscountsParams creates a new DeleteDiscountsParams object
// with the default values initialized.
func NewDeleteDiscountsParams() *DeleteDiscountsParams {
	var ()
	return &DeleteDiscountsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteDiscountsParamsWithTimeout creates a new DeleteDiscountsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteDiscountsParamsWithTimeout(timeout time.Duration) *DeleteDiscountsParams {
	var ()
	return &DeleteDiscountsParams{

		timeout: timeout,
	}
}

// NewDeleteDiscountsParamsWithContext creates a new DeleteDiscountsParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteDiscountsParamsWithContext(ctx context.Context) *DeleteDiscountsParams {
	var ()
	return &DeleteDiscountsParams{

		Context: ctx,
	}
}

// NewDeleteDiscountsParamsWithHTTPClient creates a new DeleteDiscountsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteDiscountsParamsWithHTTPClient(client *http.Client) *DeleteDiscountsParams {
	var ()
	return &DeleteDiscountsParams{
		HTTPClient: client,
	}
}

/*DeleteDiscountsParams contains all the parameters to send to the API endpoint
for the delete discounts operation typically these are written to a http.Request
*/
type DeleteDiscountsParams struct {

	/*Body*/
	Body *models.OpenpitrixDeleteDiscountsRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete discounts params
func (o *DeleteDiscountsParams) WithTimeout(timeout time.Duration) *DeleteDiscountsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete discounts params
func (o *DeleteDiscountsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete discounts params
func (o *DeleteDiscountsParams) WithContext(ctx context.Context) *DeleteDiscountsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete discounts params
func (o *DeleteDiscountsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete discounts params
func (o *DeleteDiscountsParams) WithHTTPClient(client *http.Client) *DeleteDiscountsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete discounts params
func (o *DeleteDiscountsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the delete discounts params
func (o *DeleteDiscountsParams) WithBody(body *models.OpenpitrixDeleteDiscountsRequest) *DeleteDiscountsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the delete discounts params
func (o *DeleteDiscountsParams) SetBody(body *models.OpenpitrixDeleteDiscountsRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteDiscountsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
