// Code generated by go-swagger; DO NOT EDIT.

package promotion_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"openpitrix.io/openpitrix/test/models"
)

// DeleteCouponsReader is a Reader for the DeleteCoupons structure.
type DeleteCouponsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteCouponsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteCouponsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteCouponsOK creates a DeleteCouponsOK with default headers values
func NewDeleteCouponsOK() *DeleteCouponsOK {
	return &DeleteCouponsOK{}
}

/*DeleteCouponsOK handles this case with default header values.

A successful response.
*/
type DeleteCouponsOK struct {
	Payload *models.OpenpitrixDeleteCouponsResponse
}

func (o *DeleteCouponsOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/billing/coupons][%d] deleteCouponsOK  %+v", 200, o.Payload)
}

func (o *DeleteCouponsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OpenpitrixDeleteCouponsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
