// Code generated by go-swagger; DO NOT EDIT.

package promotion_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDescribeDiscountsParams creates a new DescribeDiscountsParams object
// with the default values initialized.
func NewDescribeDiscountsParams() *DescribeDiscountsParams {
	var ()
	return &DescribeDiscountsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDescribeDiscountsParamsWithTimeout creates a new DescribeDiscountsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDescribeDiscountsParamsWithTimeout(timeout time.Duration) *DescribeDiscountsParams {
	var ()
	return &DescribeDiscountsParams{

		timeout: timeout,
	}
}

// NewDescribeDiscountsParamsWithContext creates a new DescribeDiscountsParams object
// with the default values initialized, and the ability to set a context for a request
func NewDescribeDiscountsParamsWithContext(ctx context.Context) *DescribeDiscountsParams {
	var ()
	return &DescribeDiscountsParams{

		Context: ctx,
	}
}

// NewDescribeDiscountsParamsWithHTTPClient creates a new DescribeDiscountsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDescribeDiscountsParamsWithHTTPClient(client *http.Client) *DescribeDiscountsParams {
	var ()
	return &DescribeDiscountsParams{
		HTTPClient: client,
	}
}

/*DescribeDiscountsParams contains all the parameters to send to the API endpoint
for the describe discounts operation typically these are written to a http.Request
*/
type DescribeDiscountsParams struct {

	/*DiscountID*/
	DiscountID *string
	/*Limit*/
	Limit *int64
	/*Name*/
	Name *string
	/*Offset*/
	Offset *int64
	/*Owner*/
	Owner *string
	/*Reverse*/
	Reverse *bool
	/*SortKey*/
	SortKey *string
	/*Status*/
	Status *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the describe discounts params
func (o *DescribeDiscountsParams) WithTimeout(timeout time.Duration) *DescribeDiscountsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the describe discounts params
func (o *DescribeDiscountsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the describe discounts params
func (o *DescribeDiscountsParams) WithContext(ctx context.Context) *DescribeDiscountsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the describe discounts params
func (o *DescribeDiscountsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the describe discounts params
func (o *DescribeDiscountsParams) WithHTTPClient(client *http.Client) *DescribeDiscountsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the describe discounts params
func (o *DescribeDiscountsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDiscountID adds the discountID to the describe discounts params
func (o *DescribeDiscountsParams) WithDiscountID(discountID *string) *DescribeDiscountsParams {
	o.SetDiscountID(discountID)
	return o
}

// SetDiscountID adds the discountId to the describe discounts params
func (o *DescribeDiscountsParams) SetDiscountID(discountID *string) {
	o.DiscountID = discountID
}

// WithLimit adds the limit to the describe discounts params
func (o *DescribeDiscountsParams) WithLimit(limit *int64) *DescribeDiscountsParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the describe discounts params
func (o *DescribeDiscountsParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithName adds the name to the describe discounts params
func (o *DescribeDiscountsParams) WithName(name *string) *DescribeDiscountsParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the describe discounts params
func (o *DescribeDiscountsParams) SetName(name *string) {
	o.Name = name
}

// WithOffset adds the offset to the describe discounts params
func (o *DescribeDiscountsParams) WithOffset(offset *int64) *DescribeDiscountsParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the describe discounts params
func (o *DescribeDiscountsParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WithOwner adds the owner to the describe discounts params
func (o *DescribeDiscountsParams) WithOwner(owner *string) *DescribeDiscountsParams {
	o.SetOwner(owner)
	return o
}

// SetOwner adds the owner to the describe discounts params
func (o *DescribeDiscountsParams) SetOwner(owner *string) {
	o.Owner = owner
}

// WithReverse adds the reverse to the describe discounts params
func (o *DescribeDiscountsParams) WithReverse(reverse *bool) *DescribeDiscountsParams {
	o.SetReverse(reverse)
	return o
}

// SetReverse adds the reverse to the describe discounts params
func (o *DescribeDiscountsParams) SetReverse(reverse *bool) {
	o.Reverse = reverse
}

// WithSortKey adds the sortKey to the describe discounts params
func (o *DescribeDiscountsParams) WithSortKey(sortKey *string) *DescribeDiscountsParams {
	o.SetSortKey(sortKey)
	return o
}

// SetSortKey adds the sortKey to the describe discounts params
func (o *DescribeDiscountsParams) SetSortKey(sortKey *string) {
	o.SortKey = sortKey
}

// WithStatus adds the status to the describe discounts params
func (o *DescribeDiscountsParams) WithStatus(status *string) *DescribeDiscountsParams {
	o.SetStatus(status)
	return o
}

// SetStatus adds the status to the describe discounts params
func (o *DescribeDiscountsParams) SetStatus(status *string) {
	o.Status = status
}

// WriteToRequest writes these params to a swagger request
func (o *DescribeDiscountsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.DiscountID != nil {

		// query param discount_id
		var qrDiscountID string
		if o.DiscountID != nil {
			qrDiscountID = *o.DiscountID
		}
		qDiscountID := qrDiscountID
		if qDiscountID != "" {
			if err := r.SetQueryParam("discount_id", qDiscountID); err != nil {
				return err
			}
		}

	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.Name != nil {

		// query param name
		var qrName string
		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {
			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}

	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	if o.Owner != nil {

		// query param owner
		var qrOwner string
		if o.Owner != nil {
			qrOwner = *o.Owner
		}
		qOwner := qrOwner
		if qOwner != "" {
			if err := r.SetQueryParam("owner", qOwner); err != nil {
				return err
			}
		}

	}

	if o.Reverse != nil {

		// query param reverse
		var qrReverse bool
		if o.Reverse != nil {
			qrReverse = *o.Reverse
		}
		qReverse := swag.FormatBool(qrReverse)
		if qReverse != "" {
			if err := r.SetQueryParam("reverse", qReverse); err != nil {
				return err
			}
		}

	}

	if o.SortKey != nil {

		// query param sort_key
		var qrSortKey string
		if o.SortKey != nil {
			qrSortKey = *o.SortKey
		}
		qSortKey := qrSortKey
		if qSortKey != "" {
			if err := r.SetQueryParam("sort_key", qSortKey); err != nil {
				return err
			}
		}

	}

	if o.Status != nil {

		// query param status
		var qrStatus string
		if o.Status != nil {
			qrStatus = *o.Status
		}
		qStatus := qrStatus
		if qStatus != "" {
			if err := r.SetQueryParam("status", qStatus); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
