// Code generated by go-swagger; DO NOT EDIT.

package promotion_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"openpitrix.io/openpitrix/test/models"
)

// DescribeCouponReceivedsReader is a Reader for the DescribeCouponReceiveds structure.
type DescribeCouponReceivedsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DescribeCouponReceivedsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDescribeCouponReceivedsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDescribeCouponReceivedsOK creates a DescribeCouponReceivedsOK with default headers values
func NewDescribeCouponReceivedsOK() *DescribeCouponReceivedsOK {
	return &DescribeCouponReceivedsOK{}
}

/*DescribeCouponReceivedsOK handles this case with default header values.

A successful response.
*/
type DescribeCouponReceivedsOK struct {
	Payload *models.OpenpitrixDescribeCouponReceivedsResponse
}

func (o *DescribeCouponReceivedsOK) Error() string {
	return fmt.Sprintf("[GET /v1/billing/coupon/receiveds][%d] describeCouponReceivedsOK  %+v", 200, o.Payload)
}

func (o *DescribeCouponReceivedsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OpenpitrixDescribeCouponReceivedsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
