// Code generated by go-swagger; DO NOT EDIT.

package promotion_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"openpitrix.io/openpitrix/test/models"
)

// ModifyProbationReader is a Reader for the ModifyProbation structure.
type ModifyProbationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ModifyProbationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewModifyProbationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewModifyProbationOK creates a ModifyProbationOK with default headers values
func NewModifyProbationOK() *ModifyProbationOK {
	return &ModifyProbationOK{}
}

/*ModifyProbationOK handles this case with default header values.

A successful response.
*/
type ModifyProbationOK struct {
	Payload *models.OpenpitrixModifyProbationResponse
}

func (o *ModifyProbationOK) Error() string {
	return fmt.Sprintf("[PUT /v1/billing/probation][%d] modifyProbationOK  %+v", 200, o.Payload)
}

func (o *ModifyProbationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OpenpitrixModifyProbationResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
